### ISSUE TITLE
Tin-related items and bronze blocks cannot be broken with a stone pickaxe

### ISSUE THREAD

**Issue by EvanHsieh0415** [Liyze09/Create-Metal#1]
item list:
```json
[
    "create_metal:tin_ore",
    "create_metal:deepslate_tin_ore",
    "create_metal:raw_tin_block",
    "create_metal:tin_block",
    "create_metal:bronze_block"
]
```

- Mod Loader: Fabric
- Game Version: 1.19.2
- Mod Version: 0.1e

**Comment by Liyze09** [comment]
Fixed in 0.1f. ONLY ON MODRINTH

**Comment by Liyze09** [comment]
Fixed

**Comment by yojnanjoy** [comment]
Using Modrinth download of 0.1f, still can't mine tin ores

**Comment by Liyze09** [comment]
I'm sure it is fixed this time :(

**Comment by Liyze09** [comment]
I'M SURE IT IS FIXED IN 0.1G

**Comment by yojnanjoy** [comment]
I'm using 0.1g now, and I can mine the blocks! However, they don't drop anything.. Putting it here because I suppose it's related?

**Comment by EvanHsieh0415** [comment]
> I'm using 0.1g now, and I can mine the blocks! However, they don't drop anything.. Putting it here because I suppose it's related?

maybe need to check the loot table?

**Comment by Liyze09** [comment]
Oh sorry, some loot table is failed to create,
I will fix it in one week.

**Comment by Liyze09** [comment]
Fixed in [0.1f](https://modrinth.com/mod/create-metal/version/CmnLFtcA)

**Comment by Czompi** [comment]
It is still broken on the version, you mentioned. I just figured out the problem and created a PR (#4) to fix it.
